config/routes.rb
Rails.application.routes.draw do
  get '/homes' => 'home#index', as:'homes'
  get '/homes/new' => 'home#new', as: 'new_blog'
  post 'homes' => 'home#create'
  get '/homes/:id' => 'home#show', as: 'home'
  delete 'homes/:id' => 'home#destroy', as: 'delete_home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @homes = Home.all
    end

    def show 
        @home = Home.find(params[:id])
    end    
    def new
        @home = Home.new
    end


    def create 
        @home = Home.create(home_params)
        redirect_to homes_path
    
    end
    
    def destroy
        @home = Home.find(params[:id]) 
        if @home.destroy
          redirect_to homes_path
        end
      end




      private
      def home_params
        params.require(:home).permit(:title, :content)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <h1>Our Blog</h1>
    
    <ul>
        <% @homes.each do |home| %>        
        <li><%= link_to home.title, home_path(home.id) %></li>
        <% end %>
    </ul>

    <p><%= link_to 'New Blog', new_blog_path %></p>

app/views/home/new.html.erb
<h3>Add a New Blog</h3>
<%= form_with model: @home do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>

  <br>
  <%= form.submit 'Add Blog' %>
<% end %>

<p><%= link_to 'back to blogs', homes_path %></p>

app/views/home/show.html.erb
<h3> <%= @home.title %> </h3>
<p><%= @home.content %></p>
<p><%= link_to 'back to blogs', homes_path %></p>
<p><%= button_to 'Remove Blog', delete_home_path, method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>